services:
  - type: web
    name: stock-price-prediction
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
